"""file hashing

Revision ID: 02da2d18b1ab
Revises: 3275deff618c
Create Date: 2026-01-27 20:47:27.563268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02da2d18b1ab'
down_revision: Union[str, Sequence[str], None] = '48b51be0793c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    new_col = sa.Column('file_hash', sa.BOOLEAN(), nullable=False)
    op.add_column(table_name='file_report', column=new_col)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(table_name='file_report', column_name='file_hash')
    # ### end Alembic commands ###
