"""initial-revision

Revision ID: 3275deff618c
Revises:
Create Date: 2026-01-21 01:48:05.310885
Related Issue:
Description: This is the initial database revision. Downgrading below this version will clear data.db.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.database.utils.column_statistic_serializer import ColumnStatisticSerializer

# revision identifiers, used by Alembic.
revision: str = '3275deff618c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_report',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('project_name', sa.String(), nullable=True),
                    sa.Column('project_path', sa.String(), nullable=True),
                    sa.Column('project_start_date', sa.Date(), nullable=True),
                    sa.Column('project_end_date', sa.Date(), nullable=True),
                    sa.Column('project_skills_demonstrated',
                              ColumnStatisticSerializer(), nullable=True),
                    sa.Column('is_group_project', sa.Boolean(), nullable=True),
                    sa.Column('total_authors', sa.Integer(), nullable=True),
                    sa.Column('authors_per_file',
                              ColumnStatisticSerializer(), nullable=True),
                    sa.Column('user_commit_percentage',
                              sa.Float(), nullable=True),
                    sa.Column('total_contribution_percentage',
                              sa.Float(), nullable=True),
                    sa.Column('coding_language_ratio',
                              ColumnStatisticSerializer(), nullable=True),
                    sa.Column('total_project_lines',
                              sa.Integer(), nullable=True),
                    sa.Column('activity_type_contributions',
                              ColumnStatisticSerializer(), nullable=True),
                    sa.Column('project_frameworks',
                              ColumnStatisticSerializer(), nullable=True),
                    sa.Column('project_tags',
                              ColumnStatisticSerializer(), nullable=True),
                    sa.Column('project_themes',
                              ColumnStatisticSerializer(), nullable=True),
                    sa.Column('project_tone', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_report',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('user_start_date', sa.Date(), nullable=True),
                    sa.Column('user_end_date', sa.Date(), nullable=True),
                    sa.Column('user_skills',
                              ColumnStatisticSerializer(), nullable=True),
                    sa.Column('user_coding_language_ratio',
                              ColumnStatisticSerializer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('association_table',
                    sa.Column('project_report_id',
                              sa.Integer(), nullable=False),
                    sa.Column('user_report_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['project_report_id'], [
                        'project_report.id'], ),
                    sa.ForeignKeyConstraint(['user_report_id'], [
                                            'user_report.id'], ),
                    sa.PrimaryKeyConstraint(
                        'project_report_id', 'user_report_id')
                    )
    op.create_table('file_report',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('filepath', sa.String(), nullable=True),
                    sa.Column('lines_in_file', sa.Integer(), nullable=True),
                    sa.Column('date_created', sa.Date(), nullable=True),
                    sa.Column('date_modified', sa.Date(), nullable=True),
                    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
                    sa.Column('ratio_of_individual_contribution',
                              sa.Float(), nullable=True),
                    sa.Column('skills_demonstrated',
                              ColumnStatisticSerializer(), nullable=True),
                    sa.Column('type_of_file',
                              ColumnStatisticSerializer(), nullable=True),
                    sa.Column('word_count', sa.Integer(), nullable=True),
                    sa.Column('character_count', sa.Integer(), nullable=True),
                    sa.Column('sentence_count', sa.Integer(), nullable=True),
                    sa.Column('readme_keyphrases',
                              ColumnStatisticSerializer(), nullable=True),
                    sa.Column('readme_themes',
                              ColumnStatisticSerializer(), nullable=True),
                    sa.Column('readme_tone', sa.String(), nullable=True),
                    sa.Column('number_of_functions',
                              sa.Integer(), nullable=True),
                    sa.Column('number_of_classes',
                              sa.Integer(), nullable=True),
                    sa.Column('number_of_interfaces',
                              sa.Integer(), nullable=True),
                    sa.Column('imported_packages',
                              ColumnStatisticSerializer(), nullable=True),
                    sa.Column('percentage_lines_committed',
                              sa.Float(), nullable=True),
                    sa.Column('coding_language',
                              ColumnStatisticSerializer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['project_id'], ['project_report.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_report')
    op.drop_table('association_table')
    op.drop_table('user_report')
    op.drop_table('project_report')
    # ### end Alembic commands ###
