"""Added CONTRIBUTED_TO flag

Revision ID: 48b51be0793c
Revises: 3275deff618c
Create Date: 2026-01-27 19:57:52.444530
Related Issue: https://github.com/COSC-499-W2025/capstone-project-team-18/issues/375
Description: This revision adds the contributed_to flag as a new statistic as part of the file_report table

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b51be0793c'
down_revision: Union[str, Sequence[str], None] = '8db302597900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    new_col = sa.Column('contributed_to', sa.BOOLEAN(), nullable=False)
    op.add_column(table_name='file_report', column=new_col)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(table_name='file_report', column_name='contributed_to')
    # ### end Alembic commands ###
