"""add thumbnail col to project_report

Revision ID: a5249b44f9dd
Revises: bec144c21288 (Create resume table & resume_proj_assoc)
Create Date: 2026-01-22 00:51:27.495218
Related Issue: https://github.com/COSC-499-W2025/capstone-project-team-18/issues/361
Description: Create a new thumbnail column in the project_report table to store a thumbnails file path
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5249b44f9dd'
down_revision: Union[str, Sequence[str], None] = 'bec144c21288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_report', sa.Column(
        'thumbnail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_report', 'thumbnail')
    # ### end Alembic commands ###
