"""
GitHub Pages deployment service.

Deploys a static portfolio site (generated by `export_service.py`) to a
repo on the user's account named `portfolio`. A few possibilities are handled here.
    1. The user doesn't have a repo called `portfolio` - Make a new repo and upload the portfolio
    2. The user has a `portfolio`, but it is archived or private - Throw error message
    3. The user has a `portfolio`, and it is public - Wipe it and upload the portfolio

Pages URL:  https://{username}.github.io/portfolio
"""

import base64
import io
import zipfile

import httpx
from fastapi import HTTPException

_GITHUB_API = "https://api.github.com"
_REPO_NAME = "portfolio"
_HEADERS = {
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2026-03-10",
}


def _auth_headers(token: str) -> dict:
    return {**_HEADERS, "Authorization": f"Bearer {token}"}


async def _get_username(client: httpx.AsyncClient, token: str) -> str:
    """ Retrieve the user's GitHub username. """
    resp = await client.get(f"{_GITHUB_API}/user", headers=_auth_headers(token))
    if resp.status_code != 200:
        raise HTTPException(
            status_code=502, detail="Failed to retrieve GitHub user info")

    return resp.json()["login"]


async def _validate_repo(client: httpx.AsyncClient, token: str, username: str) -> str:
    """
    Ensure the portfolio repo exists (creates a new one if not), is not archived,
    and is public.

    Returns the repo's default branch name (e.g. "main").
    """
    resp = await client.get(
        f"{_GITHUB_API}/repos/{username}/{_REPO_NAME}",
        headers=_auth_headers(token),
    )

    if resp.status_code == 200:
        data = resp.json()
        if data.get("archived") or data.get("private"):
            raise HTTPException(
                status_code=409,
                detail=(
                    f"The GitHub repository '{username}/{_REPO_NAME}' is archived or private and "
                    "cannot be modified. Please unarchive, rename, or delete the repo on GitHub "
                    "so a new portfolio can be deployed."
                ),
            )
        else:
            return data.get("default_branch", "main")

    if resp.status_code != 404:
        raise HTTPException(
            status_code=502, detail="Unable to check repository")

    create_resp = await client.post(
        f"{_GITHUB_API}/user/repos",
        headers=_auth_headers(token),
        json={
            "name": _REPO_NAME,
            "description": "My portfolio",
            "auto_init": True,
            "private": False,
        },
    )
    if create_resp.status_code not in (200, 201):
        raise HTTPException(
            status_code=502, detail="Failed to create repository")

    return create_resp.json().get("default_branch", "main")


async def _replace_all_files(
    client: httpx.AsyncClient,
    token: str,
    username: str,
    branch: str,
    files: dict[str, bytes],
    commit_message: str,
) -> None:
    """
    Wipes the portfolio repo, then commits and pushes `files`, which are
    the files that make up the generated static portfolio website.
    """
    # Get the current HEAD commit
    ref_resp = await client.get(
        f"{_GITHUB_API}/repos/{username}/{_REPO_NAME}/git/ref/heads/{branch}",
        headers=_auth_headers(token),
    )
    if ref_resp.status_code != 200:
        raise HTTPException(
            status_code=502, detail="Failed to get branch reference")
    parent_sha = ref_resp.json()["object"]["sha"]

    # Create a blob for every file
    tree_entries = []
    for path, content in files.items():
        blob_resp = await client.post(
            f"{_GITHUB_API}/repos/{username}/{_REPO_NAME}/git/blobs",
            headers=_auth_headers(token),
            json={"content": base64.b64encode(content).decode(
                "utf-8"), "encoding": "base64"},
        )
        if blob_resp.status_code not in (200, 201):
            raise HTTPException(
                status_code=502, detail=f"Failed to create blob for {path}")
        tree_entries.append({
            "path": path,
            "mode": "100644",
            "type": "blob",
            "sha": blob_resp.json()["sha"],
        })

    # Create a new tree with the new blobs (wipes repo's current files)
    tree_resp = await client.post(
        f"{_GITHUB_API}/repos/{username}/{_REPO_NAME}/git/trees",
        headers=_auth_headers(token),
        json={"tree": tree_entries},
    )
    if tree_resp.status_code not in (200, 201):
        raise HTTPException(
            status_code=502, detail="Failed to create git tree")
    tree_sha = tree_resp.json()["sha"]

    # Create a commit for the new files
    commit_resp = await client.post(
        f"{_GITHUB_API}/repos/{username}/{_REPO_NAME}/git/commits",
        headers=_auth_headers(token),
        json={"message": commit_message,
              "tree": tree_sha, "parents": [parent_sha]},
    )
    if commit_resp.status_code not in (200, 201):
        raise HTTPException(
            status_code=502, detail="Failed to create git commit")
    commit_sha = commit_resp.json()["sha"]

    # Fast-forward the branch ref to the new commit
    update_resp = await client.patch(
        f"{_GITHUB_API}/repos/{username}/{_REPO_NAME}/git/refs/heads/{branch}",
        headers=_auth_headers(token),
        json={"sha": commit_sha},
    )
    if update_resp.status_code not in (200, 201):
        raise HTTPException(
            status_code=502, detail="Failed to update branch reference")


async def _enable_pages(client: httpx.AsyncClient, token: str, username: str, branch: str) -> str:
    """
    Creates a GitHub Pages site on `branch` (if it's not already enabled).
    The GitHub Pages URL is returned.

    See: https://docs.github.com/en/rest/pages/pages?apiVersion=2026-03-10&versionId=free-pro-team%40latest&restPage=api-versions#create-a-github-pages-site
    """
    enable_resp = await client.post(
        f"{_GITHUB_API}/repos/{username}/{_REPO_NAME}/pages",
        headers=_auth_headers(token),
        json={"source": {"branch": branch, "path": "/"}},
    )

    if enable_resp.status_code in (201, 409):
        info_resp = await client.get(
            f"{_GITHUB_API}/repos/{username}/{_REPO_NAME}/pages",
            headers=_auth_headers(token),
        )
        if info_resp.status_code == 200:
            return info_resp.json().get("html_url", f"https://{username}.github.io/{_REPO_NAME}")

    return f"https://{username}.github.io/{_REPO_NAME}"


async def deploy_to_github_pages(access_token: str, zip_bytes: bytes, portfolio_name: str = "Portfolio") -> str:
    """
    Deploy the static portfolio site contained in `zip_bytes` to GitHub Pages.

    Returns:
        The portfolio URL (e.g. https://PaulAtreides.github.io/portfolio).

    Raises:
        HTTPException on any GitHub API failure.
    """
    files: dict[str, bytes] = {}
    with zipfile.ZipFile(io.BytesIO(zip_bytes)) as zf:
        for name in zf.namelist():
            files[name] = zf.read(name)

    async with httpx.AsyncClient(timeout=30) as client:
        username = await _get_username(client, access_token)
        branch = await _validate_repo(client, access_token, username)

        await _replace_all_files(
            client, access_token, username, branch, files,
            commit_message=f"Deploy {portfolio_name} via Project Miner 499",
        )

        pages_url = await _enable_pages(client, access_token, username, branch)

    return pages_url
