"""
GitHub Pages deployment service.

Deploys a static portfolio site (generated by export_service.py) to a
GitHub Pages-enabled repository on the authenticated user's account.

Repo name: `portfolio`
Pages URL:  https://{username}.github.io/portfolio
"""

import base64
import io
import zipfile

import httpx
from fastapi import HTTPException

_GITHUB_API = "https://api.github.com"
_REPO_NAME = "portfolio"
_HEADERS = {"Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28"}


def _auth_headers(token: str) -> dict:
    return {**_HEADERS, "Authorization": f"Bearer {token}"}


async def _get_username(client: httpx.AsyncClient, token: str) -> str:
    resp = await client.get(f"{_GITHUB_API}/user", headers=_auth_headers(token))
    if resp.status_code != 200:
        raise HTTPException(
            status_code=502, detail="Failed to retrieve GitHub user info")
    return resp.json()["login"]


async def _ensure_repo(client: httpx.AsyncClient, token: str, username: str) -> None:
    """
    Ensure the portfolio repo exists, is not archived, and is public.
    Creates it if it doesn't exist; raises a clear error if it exists but
    is archived or private (GitHub Pages won't work in either case).
    """
    resp = await client.get(
        f"{_GITHUB_API}/repos/{username}/{_REPO_NAME}",
        headers=_auth_headers(token),
    )
    print(
        f"[_ensure_repo] GET repo status={resp.status_code} body={resp.text}")

    if resp.status_code == 200:
        data = resp.json()
        if data.get("archived"):
            raise HTTPException(
                status_code=409,
                detail=(
                    f"The GitHub repository '{username}/{_REPO_NAME}' is archived and cannot be "
                    "deployed to. Please unarchive it on GitHub or rename/delete it so DevMiner "
                    "can create a fresh one."
                ),
            )
        if data.get("private"):
            raise HTTPException(
                status_code=409,
                detail=(
                    f"The GitHub repository '{username}/{_REPO_NAME}' is private. "
                    "GitHub Pages requires a public repository on the free plan. "
                    "Please make it public or delete it so DevMiner can create a fresh public one."
                ),
            )
        return

    if resp.status_code != 404:
        raise HTTPException(
            status_code=502, detail="Failed to check GitHub repository")

    create_resp = await client.post(
        f"{_GITHUB_API}/user/repos",
        headers=_auth_headers(token),
        json={
            "name": _REPO_NAME,
            "description": "My developer portfolio (deployed by DevMiner)",
            "auto_init": True,
            "private": False,
        },
    )
    print(
        f"[_ensure_repo] POST create repo status={create_resp.status_code} body={create_resp.text}")
    if create_resp.status_code not in (200, 201):
        raise HTTPException(
            status_code=502, detail="Failed to create GitHub repository")


async def _get_file_sha(
    client: httpx.AsyncClient, token: str, username: str, path: str
) -> str | None:
    """Return the blob SHA of an existing file, or None if it doesn't exist."""
    resp = await client.get(
        f"{_GITHUB_API}/repos/{username}/{_REPO_NAME}/contents/{path}",
        headers=_auth_headers(token),
    )
    if resp.status_code == 200:
        return resp.json().get("sha")
    return None


async def _upsert_file(
    client: httpx.AsyncClient,
    token: str,
    username: str,
    path: str,
    content: bytes,
    message: str,
) -> None:
    """Create or update a single file in the repo."""
    sha = await _get_file_sha(client, token, username, path)
    body: dict = {
        "message": message,
        "content": base64.b64encode(content).decode("utf-8"),
    }
    if sha:
        body["sha"] = sha

    resp = await client.put(
        f"{_GITHUB_API}/repos/{username}/{_REPO_NAME}/contents/{path}",
        headers=_auth_headers(token),
        json=body,
    )
    print(
        f"[_upsert_file] PUT {path} status={resp.status_code} body={resp.text}")
    if resp.status_code not in (200, 201):
        raise HTTPException(
            status_code=502, detail=f"Failed to upload {path} to GitHub")


async def _enable_pages(client: httpx.AsyncClient, token: str, username: str) -> str:
    """
    Enable GitHub Pages on the main branch if not already enabled.
    Returns the GitHub Pages URL.
    """
    enable_resp = await client.post(
        f"{_GITHUB_API}/repos/{username}/{_REPO_NAME}/pages",
        headers=_auth_headers(token),
        json={"source": {"branch": "main", "path": "/"}},
    )

    if enable_resp.status_code in (201, 409):
        # 201 = just enabled, 409 = already enabled — fetch current info either way
        info_resp = await client.get(
            f"{_GITHUB_API}/repos/{username}/{_REPO_NAME}/pages",
            headers=_auth_headers(token),
        )
        if info_resp.status_code == 200:
            return info_resp.json().get("html_url", f"https://{username}.github.io/{_REPO_NAME}")

    # Fallback: construct the URL from the username
    return f"https://{username}.github.io/{_REPO_NAME}"


async def deploy_to_github_pages(access_token: str, zip_bytes: bytes) -> str:
    """
    Deploy the static portfolio site contained in `zip_bytes` to GitHub Pages.

    - Creates the `portfolio` repo on the user's account if it doesn't exist.
    - Uploads index.html, portfolio_data.js, style.css, and filter.js.
    - Enables GitHub Pages on the main branch.

    Returns:
        The GitHub Pages URL (e.g. https://username.github.io/portfolio).

    Raises:
        HTTPException on any GitHub API failure.
    """
    files: dict[str, bytes] = {}
    with zipfile.ZipFile(io.BytesIO(zip_bytes)) as zf:
        for name in zf.namelist():
            files[name] = zf.read(name)

    async with httpx.AsyncClient(timeout=30) as client:
        username = await _get_username(client, access_token)
        await _ensure_repo(client, access_token, username)

        commit_msg = "Deploy portfolio via DevMiner"
        for filename, content in files.items():
            await _upsert_file(client, access_token, username, filename, content, commit_msg)

        pages_url = await _enable_pages(client, access_token, username)

    return pages_url
